baseURL = 'https://morganmay.day/'
languageCode = 'en'
DefaultContentLanguage = "en"
title = 'Morgan Mayday'
author = 'Morgan Mayday'
theme = 'risotto'
pluralizeListTitles = false
capitalizeListTitles = false
enableInlineShortcodes = true
copyright = "Anticopyright. We all live in the public domain."

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
dateform = "2 Jan, 2006"
dateformShort = "2 Jan"
dateformNum = "01-2006-02"
dateformNumTime = "01-2006-02 15:04"
theme.palette = 'morgan-dark'

# [menu]

# [[menu.main]]
# identifier = "grimoire"
# name = "grimoire"
# url = "/grimoire/"
# weight = 10

# [markup]

# Table of contents
# Add toc = true to content front matter to enable
# [markup.tableOfContents]
# startLevel = 2
# endLevel = 3
# ordered = true

[params.about]
title = "the website of Morgan Mayday"
description = "Spellbook, blog, and weapon."
# logo = "🍚"
#logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-signal-messenger"
title = "signal"
url = "https://signal.me/#eu/ykOZBKy5mpmEKlFxs8agf5CRGE-SNXp6aoh7P4XbjxYywZYMKRJJK5oRqpXYYgMR"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "email"
url = "mailto:me@morganmay.day"

# [[params.socialLinks]]
# icon = "fa-brands fa-discord"
# title = "discord"
# url = "https://discord.com/users/505883869434740758"
